// CoGrandImport.idl : IDL source for CoGrandImport.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (CoGrandImport.tlb) and marshalling code.

//SCR00240  Changed station ID from short to long.  pjm 1-31-2006
//SCR00237: Add four methods to COM interface to support Rokkasho/NDAR requirements
//          DeleteData, DeleteDataStore, GetDataStoreStatus, GetLastError

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(BD000CB1-05DF-11D6-8176-00C04F60E89B),
		dual,
		helpstring("IGrandImport Interface"),
		pointer_default(unique),oleautomation
	]

	interface IGrandImport : IDispatch
	{
		[id(1),  helpstring("method AddData")]					HRESULT AddData([in] short sFacilityID, [in] BSTR bstrFilename, [in] VARIANT_BOOL bOverwrite, [out] BSTR* bstrResult, [out,retval] VARIANT_BOOL* pbResult);
		[id(2),  helpstring("method BackupDataStore")]			HRESULT BackupDataStore([in] short sFacilityID, [in] BSTR bstrDestinationPath, [in] VARIANT_BOOL bQuestion, [in] VARIANT_BOOL bDefault, [out,retval] VARIANT_BOOL* pbResult);
		[id(3),  helpstring("method CloseDataStore")]			HRESULT CloseDataStore();
		[id(4),  helpstring("method CreateNewDataStore")]		HRESULT CreateNewDataStore([in] short sFacilityID, [out,retval] VARIANT_BOOL* pbResult);
		[id(5),  helpstring("method DeleteData")]				HRESULT DeleteData([in] short sFacilityID, [in] long lStationID, [in] DATE dtStartDate, [in] DATE dtEndDate, [out, retval] VARIANT_BOOL* pbStatus);
		[id(6),  helpstring("method DeleteDataStore")]			HRESULT DeleteDataStore([in] short sFacilityID, [out, retval] VARIANT_BOOL* pbStatus);
		[id(7),  helpstring("method GetDataByChannel")]			HRESULT GetDataByChannel([in] short sFacilityID, [in] long lStationID, [in] short sChannelID, [in] DATE StartTime, [in] DATE EndTime,  [in,out] VARIANT *pvData, [out,retval] VARIANT_BOOL* pbResult);
		[id(8),  helpstring("method GetDataByStation")]			HRESULT GetDataByStation([in] short sFacilityID, [in] long lStationID, [in] DATE StartTime, [in] DATE EndTime, [in,out] VARIANT* pvData, [out,retval] VARIANT_BOOL* pbResult);
		[id(9),  helpstring("method GetDataStatistics")]		HRESULT GetDataStatistics([in] short sFacilityID, [in] long lStationID, [in] short sChannelID, [in] DATE StartTime, [in] DATE EndTime, [out] DATE* pActualStartTime, [out] DATE* pActualEndTime, [out] long* plNumMembers, [out,retval] VARIANT_BOOL* pbResult);
		[id(10), helpstring("method GetDataStorePath")]			HRESULT GetDataStorePath([in] short sFacilityID, [out,retval] BSTR* bstrStorePath);
		[id(11), helpstring("method GetDataStoreSize")]			HRESULT GetDataStoreSize([in] short sFacilityID, [out] double* pdSizeInBytes, [out, retval] VARIANT_BOOL* pbResult);
		[id(12), helpstring("method GetDataStoreStatus")]		HRESULT GetDataStoreStatus( [in] short sFacilityID, [out, retval] long* plStatus);
		[id(13), helpstring("method GetDataStoreTimeRange")]	HRESULT GetDataStoreTimeRange([in] short sFacilityID, [in] long lStationID, [in] VARIANT_BOOL bErrDisplay, [out] DATE* FirstTimestamp, [out]DATE* LastTimestamp, [out,retval] VARIANT_BOOL* pbResult);
		[id(14), helpstring("method GetDayStatistics")]			HRESULT GetDayStatistics([in] short sFacilityID, [in] long lStationID, [in] DATE StartTime, [in] DATE EndTime, [out] DATE* pActualStartTime, [out] DATE* pActualEndTime, [out] long* plNumMembers, [out,retval] VARIANT_BOOL* pbResult);
		[id(15), helpstring("method GetDaySummaryData")]		HRESULT GetDaySummaryData([in] short sFacilityID, [in] long lStationID, [in] DATE StartTime, [in] DATE EndTime,  [out] VARIANT* pvDay,  [out,retval] VARIANT_BOOL* pbResult);
		[id(16), helpstring("method GetFilesList")]				HRESULT GetFilesList([in] short sFacilityID, [in] BSTR bstrRootDir, [in] VARIANT_BOOL bIncludeSubDirs, [in] VARIANT_BOOL bMostRecent, [out] VARIANT* psaFilesList);
		[id(17), helpstring("method GetLastError")]				HRESULT GetLastError( [in] short sFacilityID, [in, out] BSTR *pbstrErrortext, [out, retval] long* plError);
		[id(18), helpstring("method GetParameters")]			HRESULT GetParameters([in] short sFacilityID, [out] VARIANT* pvParms, [out,retval] VARIANT_BOOL* pbResult);
		[id(19), helpstring("method InitializeDataStore")]		HRESULT InitializeDataStore([in] short sFacilityID, [in] VARIANT_BOOL bQuestion, [out, retval] VARIANT_BOOL* pbSuccess);
		[id(20), helpstring("method OpenDataStore")]			HRESULT OpenDataStore([in] short sFacilityID, [out, retval] VARIANT_BOOL* pbSuccess);
		[id(21), helpstring("method RestoreDataStore")]			HRESULT RestoreDataStore([in] short sFacilityID, [in] BSTR bstrSourcePath, [in] VARIANT_BOOL bQuestion, [in] VARIANT_BOOL bDefault, [out, retval] VARIANT_BOOL* pbResult);
		[id(22), helpstring("method SetParameters")]			HRESULT SetParameters([in] short sFacilityID, [in] VARIANT vParms, [out,retval] VARIANT_BOOL* pbResult);
	};

[
	uuid(BD000CA1-05DF-11D6-8176-00C04F60E89B),
	version(1.0),
	helpstring("CoGrandImport 1.0 Type Library")
]
library COGRANDIMPORTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(BD000CB2-05DF-11D6-8176-00C04F60E89B),
		helpstring("GrandImport Class")
	]
	coclass GrandImport
	{
		[default] interface IGrandImport;
	};
};
