#ifndef _ZAPPPRESYS_INCLUDED
#define _ZAPPPRESYS_INCLUDED 1
/*
 * (c) Copyright 1991 - 1996 Rogue Wave Software, Inc.
 * ALL RIGHTS RESERVED
 *
 * The software and information contained herein are proprietary to, and
 * comprise valuable trade secrets of, Rogue Wave Software, Inc., which
 * intends to preserve as trade secrets such software and information.
 * This software is furnished pursuant to a written license agreement and
 * may be used, copied, transmitted, and stored only in accordance with
 * the terms of such license and with the inclusion of the above copyright
 * notice.  This software and information or any other copies thereof may
 * not be provided or otherwise made available to any other person.
 *
 * Notwithstanding any other lease or license that may pertain to, or
 * accompany the delivery of, this computer software and information, the
 * rights of the Government regarding its use, reproduction and disclosure
 * are as set forth in Section 52.227-19 of the FARS Computer
 * Software-Restricted Rights clause.
 * 
 * Use, duplication, or disclosure by the Government is subject to
 * restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in
 * Technical Data and Computer Software clause at DFARS 252.227-7013.
 * Contractor/Manufacturer is Rogue Wave Software, Inc.,
 * P.O. Box 2328, Corvallis, Oregon 97339.
 *
 * This computer software and information is distributed with "restricted
 * rights."  Use, duplication or disclosure is subject to restrictions as
 * set forth in NASA FAR SUP 18-52.227-79 (April 1985) "Commercial
 * Computer Software-Restricted Rights (April 1985)."  If the Clause at
 * 18-52.227-74 "Rights in Data General" is specified in the contract,
 * then the "Alternate III" clause applies.
 *
 **************************************************************************/


#if __BORLANDC__>=0x0460
#pragma warn -aus

#endif

#if __BORLANDC__
#pragma warn -par
#pragma warn -hid
#endif



#ifdef __SC__
#ifndef __ZTC__
#define __ZTC__ 1
#endif
#endif

#ifdef Z_HMP
#define __NT__
#endif


#ifdef _MSC_VER
#define NOMINMAX 1
#define WIN32 1
#else
#define WIN32
#endif
#define OEMRESOURCE 1
#ifndef __WATCOMC__
void* operator new(unsigned int);
void operator delete(void*);
#endif

#ifdef __ZTC__
#define _huge
#define huge
#endif

#endif

