//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by RAD.RC
//
#define IDB_BITMAP1                     2
#define IDUPDATE                        3
#define IDI_NEW_RAD_REVIEW              3
#define ID_ADD_GRAPH_CFG                3
#define IDUPDATECONDITIONS              4
#define IDR_MAIN_MENU                   102
#define IDD_IMPORT_DIALOG               104
#define IDD_UPDATE_DIALOG               105
#define IDD_DIAG_SELECTFACILITY         106
#define IDD_GRAPH_DISPLAY               108
#define IDD_SUMMARIES_MARKS             109
#define IDD_GRAPH_OPTIONS               110
#define IDD_DIAG_RAWDATA                112
#define IDD_SUMMARIES_DB_DAYS           114
#define IDD_IMPORT_SOME_DIALOG          115
#define IDD_DB_SELECT                   116
#define IDD_DB_BACKUP                   117
#define IDD_FILE_BACKUP_DB              117
#define IDD_DB_RESTORE                  119
#define IDD_FILE_RESTORE_DB             119
#define IDD_DB_CLEAR                    120
#define IDD_DB_OPEN                     121
#define IDD_GRAPH_PICTURE               122
#define IDD_PLOT_PRINT_GAUGE            123
#define IDC_UPDATE_DATA_PB              124
#define IDD_UPDATE_DATA_PB              124
#define IDD_GRAPH_HELP                  125
#define IDD_RAD_PRODUCT_SUPPORT         128
#define IDD_GRAPH_START_TIME            129
#define IDD_TOOLS_INTEGRITY             130
#define IDD_TOOLS_EVENTS                131
#define IDD_SUMMARIES_EVENTS            133
#define IDD_TOOLS_EXPORT_TABLE          134
#define IDD_EVENT_SUMM_SEP              136
#define IDD_TOOLS_EXPORT_OPTION         138
#define IDD_TOOLS_RAD_ANALYSIS          139
#define IDD_SUMMARIES_DIRECTION         140
#define IDD_PIPE_CHOICE                 141
#define IDD_TOOLS_MEASUREMENTS          143
#define IDD_TOOLS_MEASUREMENTS_ADVANCED 144
#define IDD_RAD_ABOUT                   150
#define IDD_SUMMARIES_MEASUREMENTS      151
#define IDD_GRAPH_EDIT_EVENTS           152
#define IDD_MSG_BOX                     155
#define IDD_DEFS_GRAND_BITS             156
#define IDD_DEFS_SR_BITS                157
#define IDD_DEFS_MCA_BITS               158
#define IDD_SHUTDOWN                    159
#define IDD_IMPORT_TODAY_DIALOG         160
#define IDD_LOADINGPARMS                162
#define IDD_TOOLS_REVIEW_INTERVAL       163
#define IDD_GRAPH_CONFIG_NAME           164
#define IDD_GRAPH_CONFIG_NEW            165
#define IDD_MORE_GRAPH_OPTIONS          166
#define IDC_CURSOR1                     167
#define IDD_PROGRESS_MSG_AND_BAR        168
#define IDD_TWO_LINE_PROGRESS_BAR       169
#define IDI_RAD_REVIEW                  170
#define IDI_ICON1                       171
#define IDD_TOOLS_ADJUST                172
#define IDC_CURSOR2                     173
#define IDD_DEFS_BINARY_BITS            174
#define IDD_MODELESSMSG                 175
#define IDD_FILE_COPY_LOGS              176
#define IDD_FILE_BACKUP_CFG             177
#define IDD_FILE_RESTORE_CFG            178
#define IDC_IMPORT_EDIT_PATH            1005
#define IDC_UPDATE_CHC1                 1005
#define IDC_UPDATE_CHC2                 1006
#define IDC_IMPORT_PATH                 1007
#define IDC_UPDATE_CHC3                 1007
#define IDC_IMPORT_EDIT_WILDCARD        1008
#define IDC_UPDATE_CHC4                 1008
#define IDC_IMPORT_WILDCARD             1009
#define IDC_UPDATE_CHC5                 1009
#define IDC_IMPORT_OVERWRITE_BOX        1010
#define IDC_UPDATE_CHC6                 1010
#define IDC_MARK_TYPE                   1010
#define IDC_IMPORT_INITDB_BOX           1011
#define IDC_UPDATE_CHC7                 1011
#define IDC_SELECTFACILITY              1012
#define IDC_IMPORT_DEFAULT_DB           1012
#define IDC_UPDATE_CHC8                 1012
#define IDC_LOG_Y                       1012
#define IDC_SELECTFACILITYLABEL         1013
#define IDC_UPDATE_CHC9                 1013
#define IDC_OPEN_DB_LABEL               1013
#define IDC_IMPORTT_ALL_BOX             1013
#define IDC_IMPORT_SUBFOLDER_BOX        1013
#define IDC_UPDATE_CHC10                1014
#define IDCHANGE                        1014
#define IDC_IMPORTT_SUBFOLDER_BOX       1014
#define IDC_UPDATE_CHC11                1015
#define IDC_OPEN_DB_NAME                1015
#define IDC_EVENT_SUMM_COMMA            1016
#define IDC_ZOOM_TIMES_100              1016
#define IDC_VERSION_NUM                 1016
#define IDC_BIT_30                      1016
#define IDC_EVENT_SUMM_TAB              1017
#define IDC_ZOOM_AUTO_SCALE             1017
#define IDC_PRODUCT_SUPPORT             1017
#define IDC_BIT_29                      1017
#define IDC_EXPORT_SELECT               1018
#define IDC_BIT_28                      1018
#define IDC_EXPORT_DESELECT             1019
#define IDC_BIT_27                      1019
#define IDC_EXPORT_MEASUREMENTS_TABLE   1020
#define IDC_BIT_31                      1020
#define IDC_EXPORT_FAC_NAME             1021
#define IDC_BIT_26                      1021
#define IDC_BIT_25                      1022
#define IDC_EXPORT_FACILITY             1023
#define IDC_BIT_24                      1023
#define IDC_DET_ONE                     1024
#define IDC_EXPORT_CURR_DB_START        1024
#define IDC_BIT_23                      1024
#define IDC_DET_TWO                     1025
#define IDC_EXPORT_CURR_DB_END          1025
#define IDC_BIT_22                      1025
#define IDC_DET_THREE                   1026
#define IDC_EXPORT_CURR_DB_INTERVAL     1026
#define IDC_BIT_21                      1026
#define IDC_DET_FOUR                    1027
#define IDC_EXPORT_SRCH_STRTDATE        1027
#define IDC_BIT_20                      1027
#define IDC_DET_FIVE                    1028
#define IDC_EXPORT_SRCH_STRTTIME        1028
#define IDC_BIT_19                      1028
#define IDC_DET_SIX                     1029
#define IDC_SEB_ABOUT_UPPER_BAR         1029
#define IDC_EXPORT_SRCH_INTERVAL        1029
#define IDC_BIT_18                      1029
#define IDC_DET_SEVEN                   1030
#define IDC_SEB_ABOUT_LOWER_BAR         1030
#define IDC_EXPORT_INTRVL_UNITS_PL      1030
#define IDC_BIT_17                      1030
#define IDC_DET_EIGHT                   1031
#define IDC_BIT_16                      1031
#define IDC_EXPORT_TOLERANCE            1031
#define IDC_DET_NINE                    1032
#define IDC_MEAS_ADVANCED_BUTTON        1032
#define IDC_BIT_15                      1032
#define IDC_DET_TEN                     1033
#define IDC_MEAS_FACILITY               1033
#define IDC_BIT_14                      1033
#define IDC_MARK                        1034
#define IDC_MEAS_CURR_DB_START          1034
#define IDC_BIT_13                      1034
#define IDC_PLOT_WIN                    1035
#define IDC_MEAS_CURR_DB_END            1035
#define IDC_BIT_12                      1035
#define IDC_OPTIONS                     1036
#define IDC_MEAS_CURR_DB_INTERVAL       1036
#define IDC_BIT_11                      1036
#define IDC_MEAS_SRCH_STRTDATE          1037
#define IDC_MY_HELP                     1037
#define IDC_BIT_10                      1037
#define IDC_DET_PICK_ONE                1038
#define IDC_MEAS_SRCH_STRTTIME          1038
#define IDC_BIT_9                       1038
#define IDC_DET_PICK_TWO                1039
#define IDC_RD_FACILITY_LABEL           1039
#define IDC_MEAS_SRCH_INTERVAL          1039
#define IDC_DET_PICK_THREE              1040
#define IDC_MEAS_INTRVL_UNITS_PL        1040
#define IDC_BIT_8                       1040
#define IDC_DET_PICK_FOUR               1041
#define IDC_RD_STATION_LABEL            1041
#define IDC_MEAS_ALL_BUTTON             1041
#define IDC_DET_PICK_FIVE               1042
#define IDC_MEAS_NONE_BUTTON            1042
#define IDC_BIT_7                       1042
#define IDC_DET_PICK_SIX                1043
#define IDC_RD_STATION                  1043
#define IDC_MEAS_PICKTABLE              1043
#define IDC_DET_PICK_SEVEN              1044
#define IDC_RD_CURR_DB_INTERVAL_LABEL   1044
#define IDC_DET_PICK_EIGHT              1045
#define IDC_RD_CURR_DB_LABEL2           1045
#define IDC_MEAS_ADV_FACILITY           1045
#define IDC_DET_PICK_NINE               1046
#define IDC_MEAS_ADV_STATION            1046
#define IDC_BIT_6                       1046
#define IDC_DET_PICK_TEN                1047
#define IDC_MEAS_ADV_LOW_BKG            1047
#define IDC_BIT_5                       1047
#define IDC_RD_SRCH_LABEL               1048
#define IDC_MEAS_ADV_HIGH_BKG           1048
#define IDC_MEAS_DIAG_PRINT             1048
#define IDC_RD_SRCH_STRTDATE            1049
#define IDC_MEAS_ADV_EMPTY              1049
#define IDC_MEAS_SRCH_CLEAR             1049
#define IDC_MEAS_ADV_REALS_ASSAY        1050
#define IDC_BIT_4                       1050
#define IDC_MEAS_ADV_CF                 1051
#define ID_STATIC                       1051
#define IDC_BIT_3                       1051
#define IDC_MEAS_ADV_CF_NORM            1052
#define IDC_EXPORT_CURR_START           1052
#define IDC_BIT_2                       1052
#define IDC_RD_SRCH_INTERVAL            1053
#define IDC_EXPORT_CURR_END             1053
#define IDC_BIT_1                       1054
#define IDC_MEASUREMENT_SUMM_FACILITY   1055
#define IDC_BIT_0                       1055
#define IDC_MEAS_ADV_MIN_LEN            1056
#define IDC_MEASUREMENT_SUMM_CURR_DB_START 1056
#define IDC_ALL_PTS                     1056
#define IDC_MEASUREMENT_SUMM_CURR_DB_INTERVAL 1057
#define IDC_MEAS_ADV_MAX_LEN            1057
#define IDC_LOG_FILE                    1057
#define IDC_MEAS_ADV_TOTALS_ASSAY       1058
#define IDC_MEASUREMENT_SUMM_SRCH_STRTDATE 1058
#define IDC_CHATTY_BITS                 1058
#define IDC_MEAS_ADV_ANALYSIS           1059
#define IDC_MEASUREMENT_SUMM_SRCH_STRTTIME 1059
#define IDC_MEASUREMENT_SUMM_SRCH_INTERVAL 1060
#define IDC_MEAS_ADV_ADD_TIME           1060
#define IDC_RD_CURR_DB_LABEL            1061
#define IDC_MEASUREMENT_SUMM_INTRVL_UNITS_PL 1061
#define IDC_RD_SRCH_INTRVL_LABEL        1062
#define IDC_MEASUREMENT_STATION         1062
#define IDC_2LINE_PROGRESS_BAR_CANCEL   1063
#define IDC_RD_SRCH_STRTTIME            1064
#define IDC_MEASUREMENT_SUMM_CURR_DB_END 1064
#define IDC_RD_INTRVL_UNITS_PL          1065
#define IDC_EDIT_CURRENT_EVENT          1065
#define IDC_2LINE_PROGRESS_BAR_LINE1    1065
#define IDC_RD_FACILITY                 1066
#define IDC_CREATE_NEW_EVENT            1066
#define IDC_2LINE_PROGRESS_BAR_LINE2    1066
#define IDC_RD_CURR_DB_START            1067
#define IDC_DELETE_CURRENT_EVENT        1067
#define IDC_RD_CURR_DB_END              1068
#define IDC_EVENT_TYPE                  1068
#define IDC_RD_CURR_DB_INTERVAL         1069
#define IDC_EVENT_ID                    1069
#define IDC_EVENT_START_TIME            1070
#define IDC_RD_GROUP                    1071
#define IDC_EVENT_END_TIME              1071
#define IDC_PREVIOUS_EVENT              1072
#define IDC_NEXT_EVENT                  1073
#define IDC_ZOOM_OUT                    1074
#define IDC_EVENT_CHANNEL               1074
#define IDC_ZOOM_IN                     1075
#define IDC_ALWAYS_ON_TOP               1075
#define IDC_PREV_VIEW                   1077
#define IDC_MEAS_ADV_REANALYZE          1077
#define IDC_NEXT_VIEW                   1078
#define IDC_MEAS_ADV_LOW_BKG_CHECK      1078
#define IDC_VIEW_PERIOD_PL              1079
#define IDC_MEAS_ADV_HIGH_BKG_CHECK     1079
#define IDC_VIEW_PERIOD_LBL             1080
#define IDC_VIEW_PERIOD_SB              1081
#define IDC_DAYS_FACILITY_LABEL         1082
#define IDC_EXPORT_ALL_BUTTON           1082
#define IDC_DAYS_FACILITY               1083
#define IDC_EXPORT_NONE_BUTTON          1083
#define IDC_DAYS_STATION_LABEL          1084
#define IDC_EXPORT_PICKTABLE            1084
#define IDC_DAYS_STATION                1085
#define IDC_UPDATE_GRAPH                1085
#define IDC_DAYS_CURR_DB_LABEL          1086
#define IDC_CHAN_EVENT_SUMM_SORT        1086
#define IDC_IMPORT_BROWSE               1086
#define IDC_DAYS_CURR_DB_START          1087
#define IDC_MESSAGE_BOX_TEXT            1087
#define IDC_DAYS_CURR_DB_LABEL2         1088
#define IDC_EXPORT_ASSAY                1088
#define IDC_DAYS_CURR_DB_END            1089
#define IDC_EXPORT_CF                   1089
#define IDC_RD_CURR_DAYS_INTERVAL_LABEL 1090
#define IDC_EXPORT_NORM_BKG             1090
#define IDC_DAYS_CURR_DB_INTERVAL       1091
#define IDC_EXPORT_EMPTY_ASSAY          1091
#define IDC_DAYS_SRCH_LABEL             1092
#define IDC_EXPORT_TOTALS_ASSAY         1092
#define IDC_DAYS_SRCH_STRTDATE          1093
#define IDC_EXPORT_CHANNEL              1093
#define IDC_DAYS_SRCH_STRTTIME          1094
#define IDC_DAYS_SRCH_INTRVL_LABEL      1095
#define IDC_MEAS_SUMM_GROUP             1095
#define IDC_DAYS_SRCH_INTERVAL          1096
#define IDC_MEAS_SUMM_ASSAY             1096
#define IDC_DAYS_INTRVL_UNITS_PL        1097
#define IDC_MEAS_SUMM_CF_NORM           1097
#define IDC_MEAS_SUMM_STATIC_BKG        1098
#define IDC_SOME_EDIT_PATH              1099
#define IDC_MEAS_SUMM_TOTALS            1099
#define IDC_SOME_EDIT_WILDCARD          1100
#define IDC_SDB_EDIT_NEW_PATH           1100
#define IDC_MEAS_SUMM_CF_CHECK          1100
#define IDC_SOME_OVERWRITE              1101
#define IDC_SDB_NEW_PATH_LABEL          1101
#define IDC_MEAS_SUMM_EMPTY             1101
#define IDC_SOME_INITDB                 1102
#define IDC_SELECT_ALL                  1102
#define IDC_DESELECT_ALL                1103
#define IDC_SOME_SUBFOLDER_BOX          1105
#define IDC_DSP_BIT_DEFS                1106
#define IDC_IMPORT_PICKTABLE            1108
#define IDC_IMPORTT_DEFAULT_DB_NAME     1108
#define IDC_ALL_BUTTON                  1109
#define IDC_IMPORTT_EDIT_PATH           1109
#define IDC_NONE_BUTTON                 1110
#define IDC_IMPORTT_EDIT_WILDCARD       1110
#define IDC_UPDATE_TABLE                1111
#define IDC_SDB_CURR_DB                 1111
#define IDC_IMPORTT_OVERWRITE_BOX       1111
#define IDC_BDB_CUR_PATH_LABEL          1112
#define IDC_IMPORTT_INITDB_BOX          1112
#define IDC_BDB_CURR_DB                 1113
#define IDC_IMPORTT_BROWSE              1113
#define IDC_BDB_NEW_PATH_LABEL          1114
#define IDC_SOME_BROWSE                 1114
#define IDC_BDB_EDIT_NEW_PATH           1115
#define IDC_REVIEW_FACILITY             1115
#define IDC_RDB_EDIT_BACKPATH           1116
#define IDC_REVIEW_CURR_DB_START        1116
#define IDC_REVIEW_CURR_DB_END          1117
#define IDC_RDB_BACKPATH_LABEL          1118
#define IDC_REVIEW_CURR_DB_INTERVAL     1118
#define IDC_RDB_COPYPATH_LABEL          1119
#define IDC_REVIEW_SRCH_STRTDATE        1119
#define IDC_RDB_EDIT_COPYPATH           1120
#define IDC_REVIEW_SRCH_STRTTIME        1120
#define IDC_CDB_PATH_LABEL              1121
#define IDC_REVIEW_SRCH_INTERVAL        1121
#define IDC_CDB_EDIT_PATH               1122
#define IDC_CDB_INFOLABEL               1123
#define IDC_PICTURE_PANE                1124
#define IDC_PRINT_GRAPH                 1125
#define IDC_PROGRESS_GAUGE              1126
#define IDC_GRAPH_OPT_START_TIME        1126
#define IDC_GRAPH_CONFIG                1126
#define IDC_ZOOM_FACTOR_DSP             1127
#define IDC_GRAPH_OPT_CENTER_TIME       1127
#define IDC_GRAPH_NEW_CONFIG_NAME       1127
#define IDC_GRAPH_OPT_READ_CFG          1128
#define IDC_START_TIME_RADIO            1128
#define IDC_GRAPH_OPT_WRITE_CFG         1129
#define IDC_CENTER_TIME_RADIO           1129
#define IDC_READ_CFG_RADIO              1130
#define IDC_WRITE_CFG_RADIO             1131
#define IDC_VIEW_GROUP_BOX              1132
#define IDC_DELETE_CFG_RADIO            1132
#define IDC_WHICH_VIEW_DSP              1133
#define IDC_UPDATE_CFG_RADIO            1133
#define IDC_GRAPH_CONFIG_NAME_EDIT      1134
#define IDC_GRAPH_CONFIG_NAME_LIST      1135
#define IDC_ZOOM_FACTOR_SB              1136
#define IDC_GRAPH_TIME_GROUP            1136
#define IDC_START_DATE                  1137
#define IDC_START_TIME                  1138
#define IDC_DAY_SB                      1139
#define IDC_HOUR_SB                     1140
#define IDC_MINUTE_SB                   1141
#define IDC_GRAPH_CFG_GROUP             1142
#define IDC_DAY_SB1                     1143
#define IDC_GRAPH_CFG_GROUP3            1143
#define IDC_HOUR_SB1                    1144
#define IDC_FINISHED                    1145
#define IDC_MINUTE_SB1                  1145
#define IDC_ZOOM_LBL                    1146
#define IDC_START_DATE1                 1146
#define IDC_INTEGRITY_LABEL             1147
#define IDC_START_TIME1                 1147
#define IDC_INTEGRITY_STATION_LABEL     1148
#define IDC_INTEGRITY_STATION           1149
#define IDC_INTEGRITY_CURR_DB_LABEL     1150
#define IDC_INTEGRITY_CURR_DB_START     1151
#define IDC_INTEGRITY_CURR_DB_LABEL2    1152
#define IDC_INTEGRITY_CURR_DB_END       1153
#define IDC_INTEGRITY_CURR_DB_INTERVAL_LABEL 1154
#define IDC_INTEGRITY_CURR_DB_INTERVAL  1155
#define IDC_INTEGRITY_SRCH_LABEL        1156
#define IDC_INTEGRITY_SRCH_STRTDATE     1157
#define IDC_INTEGRITY_SRCH_STRTTIME     1158
#define IDC_INTEGRITY_SRCH_INTRVL_LABEL 1159
#define IDC_INTEGRITY_SRCH_INTERVAL     1160
#define IDC_INTEGRITY_INTRVL_UNITS_PL   1161
#define IDC_INTEGRITY_GROUP             1162
#define IDC_INTEGRITY_AC_POWER          1163
#define IDC_INTEGRITY_BATTERY_LOW       1164
#define IDC_INTEGRITY_COLDSTART         1165
#define IDC_INTEGRITY_AUTHENTICATION    1166
#define IDC_INTEGRITY_ORDER             1167
#define IDC_INTEGRITY_GAP               1168
#define IDC_INTEGRITY_FACILITY          1169
#define IDC_MEAS_SUMM_LOW_BKG           1169
#define IDC_EVENTS_LABEL                1170
#define IDC_MEAS_SUMM_HIGH_BKG          1170
#define IDC_EVENTS_FACILITY             1171
#define IDC_INTEGRITY_TOLERANCE         1171
#define IDC_EVENTS_CURR_DB_LABEL        1174
#define IDC_EVENTS_CURR_DB_START        1175
#define IDC_EVENTS_CURR_DB_LABEL2       1176
#define IDC_EVENTS_CURR_DB_END          1177
#define IDC_EVENTS_CURR_DB_INTERVAL_LABEL 1178
#define IDC_EVENTS_CURR_DB_INTERVAL     1179
#define IDC_EVENTS_SRCH_LABEL           1180
#define IDC_EVENTS_SRCH_STRTDATE        1181
#define IDC_EVENTS_SRCH_INTRVL_LABEL    1182
#define IDC_EVENTS_SRCH_INTERVAL        1183
#define IDC_EVENTS_SRCH_STRTTIME        1184
#define IDC_EVENTS_INTRVL_UNITS_PL      1185
#define IDC_CHAN_EVENTS_SRCH_PEAK_PTS   1186
#define IDC_EVENTS_LABEL3               1187
#define IDC_EVENTS_ALG_LABEL            1188
#define IDC_CHAN_EVENTS_SRCH_ALG        1189
#define IDC_EVENTS_LABEL6               1192
#define IDC_CHAN_EVENTS_SRCH_SMOOTH     1200
#define IDC_EVENTS_PRINT                1201
#define IDC_EVENTS_PICKTABLE            1202
#define IDC_EVENTS_ALL_BUTTON           1203
#define IDC_EVENTS_NONE_BUTTON          1204
#define IDC_CHAN_EVENT_SRCH_LOG_FILE    1205
#define IDC_CHAN_EVENT_SRCH_CLEAR       1206
#define IDC_IMPORT_DEFAULT_DB_NAME      1207
#define IDC_CHAN_EVENT_SRCH_FILE        1207
#define IDC_CHAN_EVENT_SUMM_LABEL1      1212
#define IDC_CHAN_EVENT_SUMM_FACILITY    1213
#define IDC_CHAN_EVENT_SUMM_LABEL2      1214
#define IDC_CHAN_EVENT_SUMM_CURR_DB_START 1215
#define IDC_CHAN_EVENT_SUMM_LABEL3      1216
#define IDC_CHAN_EVENT_SUMM_CURR_DB_END 1217
#define IDC_CHAN_EVENT_SUMM_LABEL4      1218
#define IDC_CHAN_EVENT_SUMM_CURR_DB_INTERVAL 1219
#define IDC_CHAN_EVENT_SUMM_LABEL5      1220
#define IDC_CHAN_EVENT_SUMM_SRCH_STRTDATE 1221
#define IDC_CHAN_EVENT_SUMM_SRCH_STRTTIME 1222
#define IDC_CHAN_EVENT_SUMM_LABEL6a     1223
#define IDC_CHAN_EVENT_SUMM_SRCH_INTERVAL 1224
#define IDC_CHAN_EVENT_SUMM_INTRVL_UNITS_PL 1225
#define IDC_CHAN_EVENT_SUMM_LABEL11     1226
#define IDC_CHAN_EVENT_SUMM_ALL_BUTTON  1227
#define IDC_CHAN_EVENT_SUMM_NONE_BUTTON 1228
#define IDC_CHAN_EVENT_SUMM_PICKTABLE   1229
#define IDC_DSP_BEGIN                   1231
#define IDC_SUPRESS_UPDATE              1232
#define IDC_SOME_DEFAULT_DB_NAME        1235
#define IDC_CHAN_EVENT_SUMM_LABEL9      1235
#define IDC_NUM_GRAPH_PTS               1236
#define IDC_CHAN_EVENT_SUMM_LABEL10     1236
#define IDC_CANCEL_GRAPH_READ           1237
#define IDC_CHAN_EVENT_SUMM_MIN_SEPARATION 1237
#define IDC_CHAN_EVENT_SUMM_LABEL7      1238
#define IDC_CHAN_EVENT_SUMM_LABEL8      1239
#define IDC_CHAN_EVENT_SUMM_TYPE        1240
#define IDC_CHAN_EVENT_SUMM_MAX_SEPARATION 1241
#define IDC_EVENT                       1247
#define IDC_ANLZ_LABEL                  1250
#define IDC_ANLZ_CURR_DB_LABEL          1251
#define IDC_ANLZ_CURR_DB_START          1252
#define IDC_SUMM_ANLZ_DB_LABEL2         1253
#define IDC_ANLZ_CURR_DB_END            1254
#define IDC_ANLZ_FACILITY               1255
#define IDC_ANLZ_CURR_DB_INTERVAL_LABEL 1256
#define IDC_ANLZ_CURR_DB_INTERVAL       1257
#define IDC_ANLZ_SRCH_LABEL             1258
#define IDC_ANLZ_SRCH_STRTDATE          1259
#define IDC_ANLZ_SRCH_STRTTIME          1260
#define IDC_ANLZ_SRCH_INTRVL_LABEL      1261
#define IDC_ANLZ_SRCH_INTERVAL          1262
#define IDC_ANLZ_INTRVL_UNITS_PL        1263
#define IDC_ANLZ_PAIRS_LABEL            1264
#define IDC_RAD_EVENT_SRCH_PAIRS        1265
#define IDC_ANLZ_PICKTABLE              1266
#define IDC_RAD_ANLZ_CLEAR_ALL          1267
#define IDC_RAD_LABEL                   1268
#define IDC_RAD_FACILITY                1269
#define IDC_RAD_CURR_DB_LABEL           1270
#define IDC_RAD_CURR_DB_START           1271
#define IDC_RAD_CURR_DB_LABEL2          1272
#define IDC_RAD_CURR_DB_END             1273
#define IDC_RAD_CURR_DB_INTERVAL_LABEL  1274
#define IDC_RAD_CURR_DB_INTERVAL        1275
#define IDC_RAD_SRCH_LABEL              1276
#define IDC_RAD_SRCH_STRTDATE           1277
#define IDC_RAD_SRCH_STRTTIME           1278
#define IDC_RAD_SRCH_INTRVL_LABEL       1279
#define IDC_RAD_SRCH_INTERVAL           1280
#define IDC_RAD_INTRVL_UNITS_PL         1281
#define IDC_RAD_TYPE_LABEL              1282
#define IDC_RAD_TYPE                    1283
#define IDC_RAD_SORT                    1284
#define IDC_RAD_SORT_LABEL              1285
#define IDC_BUTTON1                     1286
#define IDC_BUTTON2                     1287
#define IDC_BUTTON0                     1288
#define IDC_BUTTON3                     1289
#define IDC_BUTTON4                     1290
#define IDC_PROGRESS_BAR                1291
#define IDC_BUTTON5                     1291
#define IDC_MSG                         1292
#define IDC_BUTTON6                     1292
#define IDC_ADJUST_CHECKBOX             1293
#define IDC_BUTTON7                     1293
#define IDC_ADJUST_CURR_DB_START        1294
#define IDC_BUTTON8                     1294
#define IDC_ADJUST_CURR_DB_END          1295
#define IDC_ADJUST_CURR_DB_INTERVAL     1296
#define IDC_ADJUST_TABLE                1301
#define IDC_ADJUST_FACILITY             1302
#define IDC_RAD_EVENT_SRCH_LOG_FILE     1303
#define IDC_MESSAGE_TEXT                1304
#define IDC_EXPORT_SRCH_FILE            1305
#define IDC_ANLZ_SRCH_FILE              1306
#define IDC_EXPORT_SRCH_FILE1           1306
#define IDC_UPDATE_GRAPH_CHECK          1307
#define IDC_EXPORT_SRCH_FILE3           1307
#define IDC_EXPORT_SRCH_FILE2           1307
#define IDC_RDB_CUR_PATH_LABEL          1308
#define IDC_RDB_CURR_DB                 1309
#define IDC_CLOG_LABEL                  1310
#define IDC_CLOG_EDIT_NEW_PATH          1311
#define IDC_RCFG_BACKPATH_LABEL         1312
#define IDC_RCFG_EDIT_BACKPATH          1313
#define IDC_RCFG_CUR_PATH_LABEL         1314
#define IDC_RCFG_CURR_DB                1315
#define IDC_BCFG_CUR_PATH_LABEL         1316
#define IDC_BCFG_CURR_DB                1317
#define IDC_BCFG_NEW_PATH_LABEL         1318
#define IDC_BCFG_EDIT_NEW_PATH          1319
#define IDC_INCLUDE_BKG                 1320
#define IDC_IDC_IMPORTT_OVERWRITE_BOX   1321
#define IDC_2LINE_PROGRESS_BAR_BAR      14543
#define IDC_TABLE_COLUMN_WIDTH_CURSOR   30000
#define ID_IMPORT_TODAY                 32771
#define ID_UPDATE                       32772
#define ID_TOOLS_EXPORT_TO_INCC         32773
#define ID_SUMMARIES_MARKS              32774
#define ID_HELP_CONTENTS                32775
#define ID_HELP_SEARCH                  32776
#define ID_HELP_PRODUCTSUPPORT          32777
#define ID_SUMMARIES_MEASUREMENTS       32778
#define ID_TOOLS_DETERMINE_MEASUREMENTS 32779
#define ID_TOOLS_REVIEWPERIOD           32780
#define ID_TOOLS_ADJUSTSTATIONTIMESTAMP 32781
#define ID_TOOLS_FACILITYCONFIGURATION  32782
#define ID_TOOLS_SENSORMANAGER          32783
#define ID_TOOLS_UNITSMANAGER           32784
#define ID_FILE_BACKUP_CFG              32785
#define ID_FILE_RESTORE_CFG             32786
#define ID_FILE_COPY_LOGS               32787
#define ID_FILE_EXIT                    40001
#define ID_IMPORT_ALL                   40003
#define ID_IMPORT_SELECTED              40004
#define ID_WINDOW_TILE                  40006
#define ID_WINDOW_ARRANGEICONS          40007
#define ID_FILE_PRINTERSETUP            40008
#define ID_WINDOW_CASCADE1              40012
#define ID_TOOLS_FINDEVENTS             40013
#define ID_TOOLS_DATAINTEGRITYCHECKS    40014
#define ID_TOOLS_GRAPH                  40015
#define ID_SUMMARIES_EVENTS             40016
#define ID_DIAGNOSTICS_RAWDATA          40017
#define ID_SUMMARIES_DAYS               40018
#define ID_FILE_BACKUP_DB               40019
#define ID_FILE_RESTORE_DB              40020
#define ID_HELP_ABOUT                   40023
#define ID_TOOLS_SELECTFACILITY         40025
#define ID_TOOLS_DIRECTION_ANALYSIS     40032
#define ID_SUMMARIES_DIRECTION_EVENTS   40033

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1324
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
